### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by KyleMoran138** [meshtastic/js#65]
While trying to run ```pnpm add @meshtastic/meshtasticjs``` I get the following error ``` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@buf%2Fmeshtastic_protobufs.bufbuild_es: Not Found - 404```

This issue seems to have been created in version 2.0.13-2? Not really sure what it's about.

**Comment by beewyka819** [comment]
Try running `pnpm config set @buf:registry https://buf.build/gen/npm/v1` first.

For some reason on windows I had to keep trying the above command quite a lot before it actually worked. WSL worked perfectly first try though. Maybe I was missing something but eventually got it to work.

**Comment by sachaw** [comment]
Instructions now in readme.
