### ISSUE TITLE
Switching Atak Forwarder to work on Atak mil 4.2/4.3

### ISSUE THREAD

**Issue by GPYeshuu** [meshtastic/js#80]
Hello there

Would like to know if it's possible to modify the source code from Atak Forwarder 4.10 to make it work on Atak mil version

Currently it's running on civtak, would like to make it work on the milspec one

Sry for bad english :)

**Comment by garthvh** [comment]
The Atak Forwarder repo is here https://github.com/paulmandal/atak-forwarder
